# Generated by Django 3.0 on 2019-12-14 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_auto_20191214_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
